Repository skbrown333/CookBook, pull requests merged in 2021-06, with the labels that each got.

#72 [COOK-115, COOK-114] Twitch plugin upgrade and embed text
  public/index.html
  src/plugins/iFramePlugin.tsx
Labels: enhancement, feature

#79 [COOK-92] Sorted guides
  src/components/GuideListView/GuideListView.tsx
Labels: feature

#80 [COOK-106] multiple gfys per line
  src/components/GuideDetailView/_guide-detail-view.scss
  src/constants/constants.ts
  src/plugins/GifPlugin.tsx
Labels: feature

#82 [COOK-130] cookbook authors only
  src/components/UserInput/UserInput.tsx
Labels: bug, feature

#87 Loop plugin
  src/plugins/index.ts
  src/plugins/loopedPlugin.tsx
Labels: feature

#90 [COOK-133, COOK-131] new gfycat embed
  src/components/GuideDetailView/GuideDetailSection/_guide-detail-section.scss
  src/components/GuideDetailView/_guide-detail-view.scss
  src/components/PostListView/PostView/PostView.tsx
  src/components/PostListView/PostView/_post-view.scss
  src/constants/constants.ts
  src/plugins/GifPlugin.tsx
  src/plugins/TwitterPlugin.tsx
  src/plugins/iFramePlugin.tsx
  src/plugins/loopedPlugin.tsx
  src/styles/_general.scss
Labels: bug, feature

#97 [COOK-111] Contributor Sidebar
  src/components/ContributorSideBar/ContributorSideBar.tsx
  src/components/ContributorSideBar/_contributor-side-bar.scss
  src/components/GuideDetailView/GuideDetailView.tsx
  src/components/GuideListView/GuideCard/GuideCard.tsx
  src/components/GuideListView/GuideListView.tsx
  src/components/HomePageView/HomePageView.tsx
  src/components/HomePageView/_home-page-view.scss
  src/components/PostListView/PostView/PostView.tsx
  src/components/PostListView/PostView/_post-view.scss
  src/components/SearchCreateBar/SearchCreateBar.tsx
  src/constants/constants.ts
  src/models/User.ts
Labels: feature

#99 [COOK-122, COOK-140] add donation link, add social links
  package.json
  src/components/ContributorSideBar/ContributorSideBar.tsx
  src/components/ContributorSideBar/_contributor-side-bar.scss
  src/components/GuideDetailView/GuideDetailHeader/_guide-detail-header.scss
  src/components/GuideDetailView/GuideDetailSection/GuideDetailSection.tsx
  src/components/GuideDetailView/GuideDetailSection/_guide-detail-section.scss
  src/components/GuideDetailView/GuideDetailSideNav/GuideDetailSideNav.tsx
  src/components/GuideDetailView/GuideDetailSideNav/_guide-detail-side-nav.scss
  src/components/GuideDetailView/_guide-detail-view.scss
  src/components/GuideListView/GuideCard/GuideCard.tsx
  src/components/GuideListView/GuideCard/_guide-card.scss
  src/components/PostListView/PostView/PostView.tsx
  src/components/PostListView/PostView/_post-view.scss
  src/components/TwitchSidebar/TwitchSidebar.tsx
  src/components/TwitchSidebar/_twitch-sidebar.scss
  yarn.lock
Labels: enhancement

#102 [COOK-141] add an about page
  src/App.tsx
  src/components/AboutView/AboutView.tsx
  src/components/AboutView/_about-view.scss
  src/components/Header/Header.tsx
Labels: enhancement

#108 Fix gif urls
  src/components/PostListView/PostView/_post-view.scss
  src/plugins/GifPlugin.tsx
Labels: feature

#107 [COOK-150] update to use characters
  src/components/CharacterSelect/CharacterSelect.tsx
  src/components/GuideDetailView/GuideDetailSideNav/GuideDetailSideNav.tsx
  src/components/GuideListView/GuideCard/GuideCard.tsx
  src/components/GuideListView/GuideListView.tsx
  src/components/Header/Header.tsx
  src/components/PostListView/PostListView.tsx
  src/components/PostListView/PostView/PostView.tsx
  src/constants/constants.ts
  src/models/Character.ts
  src/models/Guide.ts
  src/models/Post.ts
  src/services/CharacterService/CharacterService.ts
Labels: feature

#117 [COOK-135] collapse all sections
  src/components/GuideDetailView/GuideDetailHeader/GuideDetailHeader.tsx
  src/components/GuideDetailView/GuideDetailView.tsx
Labels: enhancement
