Repository skbrown333/CookBook, pull requests merged in 2021-05, with the labels that each got.

#3 Deploy test
  .github/workflows/firebase-hosting-merge.yml
  .github/workflows/firebase-hosting-pull-request.yml
  .github/workflows/main.yml
  src/components/MatchupDetailView/MatchupDetailView.tsx
Labels: chore

#5 chore(MatchupDetailView): revert test changes
  src/components/MatchupDetailView/MatchupDetailView.tsx
Labels: chore

#6 [COOK-34]: Replace Matchups with Guides
  .github/pull_request_template.md
  src/App.tsx
  src/components/GuideDetailView/GuideDetailView.tsx
  src/components/GuideDetailView/_guide-detail-view.scss
  src/components/GuideListView/GuideListView.tsx
  src/components/GuideListView/_guide-list-view.scss
  src/components/MatchupListView/MatchupListView.tsx
  src/models/Character.ts
  src/models/Guide.ts
  src/models/Matchup.ts
  src/models/Post.ts
  src/models/Tag.ts
Labels: breaking change, feature

#7 [COOK-39] Setup Firebase
  .gitignore
  src/App.tsx
  src/firebase/firebase.ts
Labels: feature

#9 [COOK-31] Collapse Sections
  src/components/GuideDetailView/GuideDetailView.tsx
  src/components/GuideDetailView/_guide-detail-view.scss
Labels: feature

#8 [COOK 33] Added twitch stream sidebar
  .github/workflows/firebase-hosting-merge.yml
  firebase.json
  package.json
  src/App.test.tsx
  src/App.tsx
  src/components/GuideDetailView/GuideDetailView.tsx
  src/components/TwitchSidebar/TwitchSidebar.tsx
  src/components/TwitchSidebar/_twitch-sidebar.scss
  src/constants/constants.ts
  src/index.tsx
  src/models/TwitchStream.ts
  src/reportWebVitals.ts
  src/services/TwitchService.ts
  src/setupTests.ts
  src/store/actions.ts
  src/store/initial-state.ts
  src/store/reducers.ts
  tsconfig.json
  yarn.lock
Labels: feature

#10 [COOK-29] Drag and Drop Sections
  src/components/GuideDetailView/GuideDetailView.tsx
  src/components/GuideDetailView/_guide-detail-view.scss
Labels: feature

#11 [COOK-28] Add section button
  src/components/GuideDetailView/GuideDetailView.tsx
  src/constants/constants.ts
  src/models/Post.ts
Labels: feature

#15 [COOK-52] Make Detail Page Responsive
  src/components/GuideDetailView/GuideDetailControls/GuideDetailControls.tsx
  src/components/GuideDetailView/GuideDetailControls/_guide-detail-controls.scss
  src/components/GuideDetailView/GuideDetailSection/GuideDetailSection.tsx
  src/components/GuideDetailView/GuideDetailSection/_guide-detail-section.scss
  src/components/GuideDetailView/GuideDetailSideNav/GuideDetailSideNav.tsx
  src/components/GuideDetailView/GuideDetailSideNav/_guide-detail-side-nav.scss
  src/components/GuideDetailView/GuideDetailView.tsx
  src/components/GuideDetailView/_guide-detail-view.scss
  src/components/TwitchSidebar/_twitch-sidebar.scss
  src/constants/constants.ts
Labels: feature

#14 [COOK-51] Fix a Bug with Adding and Re-Ordering
  src/components/GuideDetailView/GuideDetailView.tsx
Labels: bug

#16 [COOK-35] Add Tags
  src/components/GuideDetailView/GuideDetailSection/GuideDetailSection.tsx
  src/components/GuideDetailView/GuideDetailView.tsx
  src/components/TagSection/TagSection.tsx
  src/components/TagSection/_tag-section.scss
  src/constants/constants.ts
  src/firebase/firebase.ts
  src/models/Tag.ts
Labels: feature

#18 [COOK-53] Delete sections
  src/components/GuideDetailView/GuideDetailControls/GuideDetailControls.tsx
  src/components/GuideDetailView/GuideDetailSection/GuideDetailSection.tsx
  src/components/GuideDetailView/GuideDetailSection/_guide-detail-section.scss
  src/components/GuideDetailView/GuideDetailView.tsx
Labels: feature

#19 [COOK-37, COOK-36] Guide List Link in Header
  public/falcon.png
  public/index.html
  public/manifest.json
  src/App.tsx
  src/components/GuideListView/GuideCard/GuideCard.tsx
  src/components/GuideListView/GuideCard/_guide-card.scss
  src/components/GuideListView/GuideListView.tsx
  src/components/GuideListView/_guide-list-view.scss
  src/components/Header/Header.tsx
Labels: feature

#21 [COOK-64] Video Iframes
  src/components/GuideDetailView/GuideDetailControls/GuideDetailControls.tsx
  src/components/GuideDetailView/GuideDetailSection/GuideDetailSection.tsx
  src/components/GuideDetailView/GuideDetailSection/_guide-detail-section.scss
  src/components/GuideDetailView/GuideDetailView.tsx
  src/constants/constants.ts
  src/plugins/GifPlugin.tsx
  src/plugins/iFramePlugin.tsx
  src/plugins/index.ts
Labels: feature

#22 [COOK-54, COOK-69, COOK-71] Guide Creation
  src/App.tsx
  src/components/CharacterSelect/CharacterSelect.tsx
  src/components/CharacterSelect/_character-select.scss
  src/components/GuideDetailView/GuideDetailSection/GuideDetailSection.tsx
  src/components/GuideListView/GuideCard/GuideCard.tsx
  src/components/GuideListView/GuideCard/_guide-card.scss
  src/components/GuideListView/GuideListView.tsx
  src/components/GuideListView/_guide-list-view.scss
  src/components/Header/Header.tsx
  src/components/TagInput/TagInput.tsx
  src/components/TagInput/_tag-input.scss
  src/components/TagSection/TagSection.tsx
  src/constants/CharacterIcons.ts
  src/constants/constants.ts
  src/firebase/firebase.ts
  src/images/bowser.png
  src/images/donkeykong.png
  src/images/drmario.png
  src/images/falco.png
  src/images/falcon.png
  src/images/fox.png
  src/images/game&watch.png
  src/images/ganondorf.png
  src/images/iceclimbers.png
  src/images/jigglypuff.png
  src/images/kirby.png
  src/images/link.png
  src/images/luigi.png
  src/images/mario.png
  src/images/marth.png
  src/images/mewtwo.png
  src/images/ness.png
  src/images/peach.png
  src/images/pichu.png
  src/images/pikachu.png
  src/images/roy.png
  src/images/samus.png
  src/images/sheik.png
  src/images/wireframe.png
  src/images/yoshi.png
  src/images/younglink.png
  src/images/zelda.png
  src/models/Cookbook.ts
  src/models/Guide.ts
  src/store/actions.ts
  src/store/initial-state.ts
  src/store/reducers.ts
Labels: feature

#32 [COOK-58, COOK-46] Gate Editing Controls
  src/components/GuideDetailView/GuideDetailView.tsx
  src/components/GuideListView/GuideCard/GuideCard.tsx
  src/components/GuideListView/GuideListView.tsx
  src/components/Header/Header.tsx
  src/firebase/firebase.ts
  src/store/initial-state.ts
Labels: feature

#34 [COOK-50] Twitch Cloud Function
  functions/src/index.ts
  src/App.tsx
  src/components/GuideDetailView/GuideDetailSideNav/_guide-detail-side-nav.scss
  src/components/TwitchSidebar/TwitchSidebar.tsx
  src/components/TwitchSidebar/_twitch-sidebar.scss
  src/constants/constants.ts
  src/firebase/firebase.ts
  src/store/actions.ts
  src/store/initial-state.ts
  src/store/reducers.ts
Labels: feature

#39 [COOK-65] Reorder by side nav
  src/components/GuideDetailView/GuideDetailSideNav/GuideDetailSideNav.tsx
  src/components/GuideDetailView/GuideDetailSideNav/_guide-detail-side-nav.scss
  src/components/GuideDetailView/GuideDetailView.tsx
  src/components/GuideDetailView/_guide-detail-view.scss
Labels: feature

#42 [COOK-87] Get Cookbook from Subdomain
  src/App.tsx
  src/components/GuideDetailView/GuideDetailSection/_guide-detail-section.scss
  src/firebase/firebase.ts
Labels: feature

#41 [COOK-60] Posts
  src/App.tsx
  src/components/GuideListView/GuideListView.tsx
  src/components/GuideListView/_guide-list-view.scss
  src/components/ListView/ListView.tsx
  src/components/ListView/_list-view.scss
  src/components/PostListView/PostListView.tsx
  src/components/PostListView/PostView/PostView.tsx
  src/components/PostListView/PostView/_post-view.scss
  src/components/PostListView/_post-list-view.scss
  src/components/SearchCreateBar/SearchCreateBar.tsx
  src/components/SearchCreateBar/_search-create-bar.scss
  src/constants/constants.ts
  src/models/Post.ts
Labels: feature

#46 [COOK-59, COOK-60] Post Card, Post Card Lazy Load
  package.json
  src/components/GuideDetailView/GuideDetailSection/_guide-detail-section.scss
  src/components/GuideListView/GuideListView.tsx
  src/components/GuideListView/_guide-list-view.scss
  src/components/PostListView/PostListView.tsx
  src/components/PostListView/PostView/PostView.tsx
  src/components/PostListView/PostView/_post-view.scss
  src/components/PostListView/_post-list-view.scss
  src/components/SearchCreateBar/_search-create-bar.scss
  src/components/TwitchSidebar/_twitch-sidebar.scss
  src/constants/constants.ts
  src/firebase/firebase.ts
  src/models/Post.ts
  src/models/TwitchStream.ts
  yarn.lock
Labels: feature

#55 [COOK-100, COOK-73, COOK-61] Add Post Authors, Add Filtering
  .eslintrc.js
  src/components/GuideListView/GuideListView.tsx
  src/components/PostListView/PostListView.tsx
  src/components/PostListView/PostView/PostView.tsx
  src/components/PostListView/PostView/_post-view.scss
  src/components/PostListView/_post-list-view.scss
  src/components/SearchCreateBar/SearchCreateBar.tsx
  src/components/SearchCreateBar/_search-create-bar.scss
  src/components/UserInput/UserInput.tsx
  src/components/UserInput/_user-input.scss
  src/firebase/firebase.ts
  src/models/Post.ts
Labels: feature

#57 [COOK-93 COOK-94] guide header and nav flyout on mobile
  package.json
  src/components/GuideDetailView/GuideDetailControls/GuideDetailControls.tsx
  src/components/GuideDetailView/GuideDetailControls/_guide-detail-controls.scss
  src/components/GuideDetailView/GuideDetailHeader/GuideDetailHeader.tsx
  src/components/GuideDetailView/GuideDetailHeader/_guide-detail-header.scss
  src/components/GuideDetailView/GuideDetailView.tsx
  src/components/GuideDetailView/_guide-detail-view.scss
  yarn.lock
Labels: feature

#60 [COOK-98] Swipe Navigation
  package.json
  src/App.scss
  src/App.tsx
  src/components/GuideListView/GuideListView.tsx
  src/components/GuideListView/_guide-list-view.scss
  src/components/HomePageView/HomePageView.tsx
  src/components/HomePageView/_home-page-view.scss
  src/components/PostListView/PostListView.tsx
  src/components/PostListView/_post-list-view.scss
  src/store/actions.ts
  src/store/initial-state.ts
  src/store/reducers.ts
  yarn.lock
Labels: feature

#66 [COOK-107] Tweet plugin
  package.json
  src/components/GuideDetailView/GuideDetailSection/_guide-detail-section.scss
  src/components/PostListView/_post-list-view.scss
  src/constants/constants.ts
  src/plugins/TwitterPlugin.tsx
  src/plugins/index.ts
  src/styles/_general.scss
  yarn.lock
Labels: feature
